# Generated by Django 6.1 on 2026-08-28 00:14
#
# Editado a mano: mismo caso que libros/migrations/0002 pero para la FK
# prestamos.Prestamo.usuario -> usuarios.Usuario. Ver el comentario de esa
# migración para el detalle del problema de SQLite que esto corrige.
from django.db import migrations, models


def fix_prestamo_usuario_fk(apps, schema_editor):
    Prestamo = apps.get_model('prestamos', 'Prestamo')
    schema_editor._remake_table(Prestamo)


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunPython(fix_prestamo_usuario_fk, fix_prestamo_usuario_fk),
    ]
