# Generated by Django 6.1 on 2026-08-28 00:15
#
# Editado a mano: se agrega un paso RunPython al final. Libro.id_libro era la
# PK y prestamos.Prestamo.libro tiene una FK hacia esa columna. En SQLite,
# renombrar/quitar la PK obliga a reconstruir la tabla libros_libro, pero esa
# reconstrucción no repara automáticamente la FK ya existente en
# prestamos_prestamo (que sigue apuntando a "id_libro"), lo que revienta la
# validación de integridad referencial al final de la migración con
# "foreign key mismatch". El paso RunPython reconstruye prestamos_prestamo
# (misma transacción/migración) para que su FK quede apuntando a la nueva
# columna "id" de libros_libro.
from django.db import migrations, models


def fix_prestamo_libro_fk(apps, schema_editor):
    Prestamo = apps.get_model('prestamos', 'Prestamo')
    schema_editor._remake_table(Prestamo)


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='id_libro',
        ),
        migrations.AddField(
            model_name='libro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunPython(fix_prestamo_libro_fk, fix_prestamo_libro_fk),
    ]
